name: Response Time CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  response_time:
    runs-on: ubuntu-latest
    steps:
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          UPPTIME_GH_PAT: ${{ secrets.GH_PAT }}
          UPDATE_RESPONSE_TIME: true
